/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mfs;

import java.awt.Dimension;

/**
 *
 * @author 102976781
 */
public class Empty extends javax.swing.JFrame {

    /**
     * Creates new form Empty500easy
     */
    
    //New String ins = String "I";
    public Empty() {
        javax.swing.JFrame frame = new javax.swing.JFrame();
        javax.swing.JButton btn = new javax.swing.JButton("Click");
        
        frame.add(btn);
        
        setPreferredSize(new Dimension(1024, 1280));
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cntr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        User500 = new javax.swing.JLabel();
        work500 = new javax.swing.JLabel();
        bloque1 = new javax.swing.JPanel();
        NPS = new javax.swing.JPanel();
        npaescanear = new javax.swing.JLabel();
        QT = new javax.swing.JLabel();
        FQT = new javax.swing.JLabel();
        DISP = new javax.swing.JLabel();
        idsp = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        npecaneado = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        cantidadrequerida = new javax.swing.JLabel();
        cantidadfinal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        check = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        NPS2 = new javax.swing.JPanel();
        npaescanear2 = new javax.swing.JLabel();
        QT2 = new javax.swing.JLabel();
        FQT2 = new javax.swing.JLabel();
        DISP2 = new javax.swing.JLabel();
        idsp2 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JLabel();
        npecaneado2 = new javax.swing.JLabel();
        serial2 = new javax.swing.JLabel();
        cantidadrequerida2 = new javax.swing.JLabel();
        cantidadfinal2 = new javax.swing.JLabel();
        NPS3 = new javax.swing.JPanel();
        npaescanear3 = new javax.swing.JLabel();
        QT3 = new javax.swing.JLabel();
        FQT3 = new javax.swing.JLabel();
        DISP3 = new javax.swing.JLabel();
        idsp3 = new javax.swing.JLabel();
        descripcion3 = new javax.swing.JLabel();
        npecaneado3 = new javax.swing.JLabel();
        serial3 = new javax.swing.JLabel();
        cantidadrequerida3 = new javax.swing.JLabel();
        cantidadfinal3 = new javax.swing.JLabel();
        NPS1 = new javax.swing.JPanel();
        npaescanear1 = new javax.swing.JLabel();
        QT1 = new javax.swing.JLabel();
        FQT1 = new javax.swing.JLabel();
        DISP1 = new javax.swing.JLabel();
        idsp1 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JLabel();
        npecaneado1 = new javax.swing.JLabel();
        serial1 = new javax.swing.JLabel();
        cantidadrequerida1 = new javax.swing.JLabel();
        cantidadfinal1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 1280));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Country: USA");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("0001 / 0001");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Mach Num: 7800KE78G");

        Cntr.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Cntr.setText("Cntr: 000063H7Q8");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Mctl:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Order: A3CMLW");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("User:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Brof: 895");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Model: S42");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Oper: 500");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Prod ID: RSRCK");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Schd: 2023-09-01");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Sys Num: 1AVM176");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("WT SYS");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        User500.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        work500.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        bloque1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS.setFocusable(false);
        NPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPSMouseClicked(evt);
            }
        });

        npaescanear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear.setText("01KL468");

        QT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT.setText("QT:");

        FQT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT.setText("FQT:");

        DISP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP.setText("IDSP:");

        idsp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp.setText("A");

        descripcion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion.setText("DESCRIPCIÓN");

        npecaneado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado.setText("PF  2L01-");

        serial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial.setText("-             -            -");

        cantidadrequerida.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida.setText("00001");

        cantidadfinal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal.setText("00000");

        javax.swing.GroupLayout NPSLayout = new javax.swing.GroupLayout(NPS);
        NPS.setLayout(NPSLayout);
        NPSLayout.setHorizontalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addComponent(DISP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp))
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addComponent(npaescanear)
                                .addGap(18, 18, 18)
                                .addComponent(QT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addComponent(cantidadrequerida)
                                .addGap(23, 23, 23)
                                .addComponent(FQT))
                            .addComponent(descripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal))
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addComponent(npecaneado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        NPSLayout.setVerticalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear)
                    .addComponent(QT)
                    .addComponent(FQT)
                    .addComponent(cantidadrequerida)
                    .addComponent(cantidadfinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP)
                    .addComponent(idsp)
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado)
                    .addComponent(serial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque1Layout = new javax.swing.GroupLayout(bloque1);
        bloque1.setLayout(bloque1Layout);
        bloque1Layout.setHorizontalGroup(
            bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bloque1Layout.createSequentialGroup()
                .addComponent(NPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bloque1Layout.setVerticalGroup(
            bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque1Layout.createSequentialGroup()
                .addComponent(NPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 597, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        check.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        check.setText("Incompleto");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/imagen.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(check)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS2.setFocusable(false);
        NPS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS2MouseClicked(evt);
            }
        });

        npaescanear2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear2.setText("69Y1649");

        QT2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT2.setText("QT:");

        FQT2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT2.setText("FQT:");

        DISP2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP2.setText("IDSP:");

        idsp2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp2.setText("A");

        descripcion2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion2.setText("DESCRIPCIÓN");

        npecaneado2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado2.setText("PF  2L01-");

        serial2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial2.setText("-             -            -");

        cantidadrequerida2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida2.setText("00001");

        cantidadfinal2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal2.setText("00000");

        javax.swing.GroupLayout NPS2Layout = new javax.swing.GroupLayout(NPS2);
        NPS2.setLayout(NPS2Layout);
        NPS2Layout.setHorizontalGroup(
            NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS2Layout.createSequentialGroup()
                        .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPS2Layout.createSequentialGroup()
                                .addComponent(DISP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp2))
                            .addGroup(NPS2Layout.createSequentialGroup()
                                .addComponent(npaescanear2)
                                .addGap(18, 18, 18)
                                .addComponent(QT2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS2Layout.createSequentialGroup()
                                .addComponent(cantidadrequerida2)
                                .addGap(23, 23, 23)
                                .addComponent(FQT2))
                            .addComponent(descripcion2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal2))
                    .addGroup(NPS2Layout.createSequentialGroup()
                        .addComponent(npecaneado2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NPS2Layout.setVerticalGroup(
            NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear2)
                    .addComponent(QT2)
                    .addComponent(FQT2)
                    .addComponent(cantidadrequerida2)
                    .addComponent(cantidadfinal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP2)
                    .addComponent(idsp2)
                    .addComponent(descripcion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado2)
                    .addComponent(serial2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS3.setFocusable(false);
        NPS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS3MouseClicked(evt);
            }
        });

        npaescanear3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear3.setText("69Y1649");

        QT3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT3.setText("QT:");

        FQT3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT3.setText("FQT:");

        DISP3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP3.setText("IDSP:");

        idsp3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp3.setText("A");

        descripcion3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion3.setText("DESCRIPCIÓN");

        npecaneado3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado3.setText("PF  2L01-");

        serial3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial3.setText("-             -            -");

        cantidadrequerida3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida3.setText("00001");

        cantidadfinal3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal3.setText("00000");

        javax.swing.GroupLayout NPS3Layout = new javax.swing.GroupLayout(NPS3);
        NPS3.setLayout(NPS3Layout);
        NPS3Layout.setHorizontalGroup(
            NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS3Layout.createSequentialGroup()
                        .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPS3Layout.createSequentialGroup()
                                .addComponent(DISP3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp3))
                            .addGroup(NPS3Layout.createSequentialGroup()
                                .addComponent(npaescanear3)
                                .addGap(18, 18, 18)
                                .addComponent(QT3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS3Layout.createSequentialGroup()
                                .addComponent(cantidadrequerida3)
                                .addGap(23, 23, 23)
                                .addComponent(FQT3))
                            .addComponent(descripcion3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal3))
                    .addGroup(NPS3Layout.createSequentialGroup()
                        .addComponent(npecaneado3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NPS3Layout.setVerticalGroup(
            NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear3)
                    .addComponent(QT3)
                    .addComponent(FQT3)
                    .addComponent(cantidadrequerida3)
                    .addComponent(cantidadfinal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP3)
                    .addComponent(idsp3)
                    .addComponent(descripcion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado3)
                    .addComponent(serial3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        NPS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS1.setFocusable(false);
        NPS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS1MouseClicked(evt);
            }
        });

        npaescanear1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear1.setText("69Y1649");

        QT1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT1.setText("QT:");

        FQT1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT1.setText("FQT:");

        DISP1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP1.setText("IDSP:");

        idsp1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp1.setText("A");

        descripcion1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion1.setText("LINE CORD, ");

        npecaneado1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado1.setText("PF  2L01-");

        serial1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial1.setText("-             -            -");

        cantidadrequerida1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida1.setText("00001");

        cantidadfinal1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal1.setText("00000");

        javax.swing.GroupLayout NPS1Layout = new javax.swing.GroupLayout(NPS1);
        NPS1.setLayout(NPS1Layout);
        NPS1Layout.setHorizontalGroup(
            NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS1Layout.createSequentialGroup()
                        .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPS1Layout.createSequentialGroup()
                                .addComponent(DISP1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp1))
                            .addGroup(NPS1Layout.createSequentialGroup()
                                .addComponent(npaescanear1)
                                .addGap(18, 18, 18)
                                .addComponent(QT1)))
                        .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPS1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida1)
                                .addGap(23, 23, 23)
                                .addComponent(FQT1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal1))
                            .addGroup(NPS1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(NPS1Layout.createSequentialGroup()
                        .addComponent(npecaneado1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        NPS1Layout.setVerticalGroup(
            NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear1)
                    .addComponent(QT1)
                    .addComponent(FQT1)
                    .addComponent(cantidadrequerida1)
                    .addComponent(cantidadfinal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP1)
                    .addComponent(idsp1)
                    .addComponent(descripcion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado1)
                    .addComponent(serial1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel8)
                                .addGap(61, 61, 61)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(User500, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(Cntr))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(208, 208, 208)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(work500, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(41, 41, 41))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bloque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(NPS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(NPS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NPS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(User500, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(Cntr)
                                .addComponent(jLabel1))
                            .addComponent(work500, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(NPS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NPS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NPS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPSMouseClicked
        all.barcode.setVisible(true);
        all.barcode.machinefinal.setVisible(false);
        all.barcode.machine.setVisible(false);
        all.barcode.country.setVisible(false);
        all.barcode.countryfinal.setVisible(false);
    }//GEN-LAST:event_NPSMouseClicked

    private void NPS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS1MouseClicked
        all.barcode_1.setVisible(true);
        all.barcode_1.otra.setVisible(false);
    }//GEN-LAST:event_NPS1MouseClicked

    private void NPS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS3MouseClicked
        all.barcode_3.setVisible(true);
        all.barcode_3.otra.setVisible(false);
    }//GEN-LAST:event_NPS3MouseClicked

    private void NPS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS2MouseClicked
        all.barcode_2.setVisible(true);
        all.barcode_2.otra.setVisible(false);
    }//GEN-LAST:event_NPS2MouseClicked

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        if(idsp.getText().equals("I") && idsp2.getText().equals("I") && idsp2.getText().equals("I") && idsp3.getText().equals("I")){
            check.setText("Completo");
            check.setSelected(true);
        // para abrir el barcode tratar de poner un IF para que valide en cual se esta usando    
        }
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cntr;
    public javax.swing.JLabel DISP;
    public javax.swing.JLabel DISP1;
    public javax.swing.JLabel DISP2;
    public javax.swing.JLabel DISP3;
    public javax.swing.JLabel FQT;
    public javax.swing.JLabel FQT1;
    public javax.swing.JLabel FQT2;
    public javax.swing.JLabel FQT3;
    public javax.swing.JPanel NPS;
    public javax.swing.JPanel NPS1;
    public javax.swing.JPanel NPS2;
    public javax.swing.JPanel NPS3;
    public javax.swing.JLabel QT;
    public javax.swing.JLabel QT1;
    public javax.swing.JLabel QT2;
    public javax.swing.JLabel QT3;
    public javax.swing.JLabel User500;
    public javax.swing.JPanel bloque1;
    public javax.swing.JLabel cantidadfinal;
    public javax.swing.JLabel cantidadfinal1;
    public javax.swing.JLabel cantidadfinal2;
    public javax.swing.JLabel cantidadfinal3;
    public javax.swing.JLabel cantidadrequerida;
    public javax.swing.JLabel cantidadrequerida1;
    public javax.swing.JLabel cantidadrequerida2;
    public javax.swing.JLabel cantidadrequerida3;
    public javax.swing.JCheckBox check;
    public javax.swing.JLabel descripcion;
    public javax.swing.JLabel descripcion1;
    public javax.swing.JLabel descripcion2;
    public javax.swing.JLabel descripcion3;
    public javax.swing.JLabel idsp;
    public javax.swing.JLabel idsp1;
    public javax.swing.JLabel idsp2;
    public javax.swing.JLabel idsp3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar1;
    public javax.swing.JLabel npaescanear;
    public javax.swing.JLabel npaescanear1;
    public javax.swing.JLabel npaescanear2;
    public javax.swing.JLabel npaescanear3;
    public javax.swing.JLabel npecaneado;
    public javax.swing.JLabel npecaneado1;
    public javax.swing.JLabel npecaneado2;
    public javax.swing.JLabel npecaneado3;
    public javax.swing.JLabel serial;
    public javax.swing.JLabel serial1;
    public javax.swing.JLabel serial2;
    public javax.swing.JLabel serial3;
    public javax.swing.JLabel work500;
    // End of variables declaration//GEN-END:variables
}
