/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mfs;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Scrollbar;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author 102976781
 */
public class Empty extends javax.swing.JFrame {


    
    
    public void extender(){
        GraphicsEnvironment env =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }
    
    int xx, yy;
    String pn;
    String nps [];
        final String label1 [] = {
        "PN","EC","SEC","MS","CN"
        };

        final String label2 [] = {
        "PN","EC","SEC","MS"
        };

        final String label3 [] = {
        "PN","EC","SEC"
        };

        final String label4 [] = {
        "PN","EC"
        };

        final String label5 [] = {
        "PN"
        };
    
    public Empty() {
        //javax.swing.JFrame frame = new javax.swing.JFrame();
        //javax.swing.JButton btn = new javax.swing.JButton("Click");
        //frame.add(btn);
        setPreferredSize(new Dimension(1070, 3000));
        //jScrollbar bar1;
        //bar1 = new Scrollbar(Scrollbar.VERTICAL,0,0,0,100);
        //bar1.addAdjustmentListener();
        this.setUndecorated(true);
        extender();
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cntr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        User500 = new javax.swing.JLabel();
        work500 = new javax.swing.JLabel();
        cuerpo = new javax.swing.JScrollPane();
        bloque1 = new javax.swing.JPanel();
        imagen = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        change = new javax.swing.JCheckBox();
        bloque1_1 = new javax.swing.JPanel();
        NPS = new javax.swing.JPanel();
        npaescanear = new javax.swing.JLabel();
        QT = new javax.swing.JLabel();
        FQT = new javax.swing.JLabel();
        DISP = new javax.swing.JLabel();
        idsp = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        npecaneado = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        cantidadrequerida = new javax.swing.JLabel();
        cantidadfinal = new javax.swing.JLabel();
        bloque2 = new javax.swing.JPanel();
        NPS3 = new javax.swing.JPanel();
        npaescanear3 = new javax.swing.JLabel();
        QT3 = new javax.swing.JLabel();
        FQT3 = new javax.swing.JLabel();
        DISP3 = new javax.swing.JLabel();
        idsp3 = new javax.swing.JLabel();
        descripcion3 = new javax.swing.JLabel();
        npecaneado3 = new javax.swing.JLabel();
        serial3 = new javax.swing.JLabel();
        cantidadrequerida3 = new javax.swing.JLabel();
        cantidadfinal3 = new javax.swing.JLabel();
        NPS2 = new javax.swing.JPanel();
        npaescanear2 = new javax.swing.JLabel();
        QT2 = new javax.swing.JLabel();
        FQT2 = new javax.swing.JLabel();
        DISP2 = new javax.swing.JLabel();
        idsp2 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JLabel();
        npecaneado2 = new javax.swing.JLabel();
        serial2 = new javax.swing.JLabel();
        cantidadrequerida2 = new javax.swing.JLabel();
        cantidadfinal2 = new javax.swing.JLabel();
        NPS1 = new javax.swing.JPanel();
        npaescanear1 = new javax.swing.JLabel();
        QT1 = new javax.swing.JLabel();
        FQT1 = new javax.swing.JLabel();
        DISP1 = new javax.swing.JLabel();
        idsp1 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JLabel();
        npecaneado1 = new javax.swing.JLabel();
        serial1 = new javax.swing.JLabel();
        cantidadrequerida1 = new javax.swing.JLabel();
        cantidadfinal1 = new javax.swing.JLabel();
        NPS5 = new javax.swing.JPanel();
        npaescanear5 = new javax.swing.JLabel();
        QT5 = new javax.swing.JLabel();
        FQT5 = new javax.swing.JLabel();
        DISP5 = new javax.swing.JLabel();
        idsp5 = new javax.swing.JLabel();
        descripcion5 = new javax.swing.JLabel();
        npecaneado5 = new javax.swing.JLabel();
        serial5 = new javax.swing.JLabel();
        cantidadrequerida5 = new javax.swing.JLabel();
        cantidadfinal5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        change1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 1280));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f2dd.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f3d.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f4d.png"))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f5d.png"))); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f6d.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f7d.png"))); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f8.png"))); // NOI18N

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/f11.png"))); // NOI18N

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/ncm.png"))); // NOI18N

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/viewcoll.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Country: USA");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("0001 / 0001");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Mach Num: 7800KE78G");

        Cntr.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Cntr.setText("Cntr: 000063H7Q8");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Mctl:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Order: A3CMLW");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("User:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Brof: 895");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Model: S42");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Oper: 500");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Prod ID: RSRCK");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Schd: 2023-09-01");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Sys Num: 1AVM176");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("WT SYS");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        User500.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        work500.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        bloque1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/rack1.png"))); // NOI18N

        change.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change.setText("Incompleto");
        change.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout imagenLayout = new javax.swing.GroupLayout(imagen);
        imagen.setLayout(imagenLayout);
        imagenLayout.setHorizontalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(change)
                    .addComponent(jLabel15))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        imagenLayout.setVerticalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bloque1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS.setFocusable(false);
        NPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPSMouseClicked(evt);
            }
        });

        npaescanear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear.setText("01KL468");

        QT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT.setText("QT:");

        FQT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT.setText("FQT:");

        DISP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP.setText("IDSP:");

        idsp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp.setText("A");

        descripcion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion.setText("MECH        C-rack +pallet");

        npecaneado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado.setText("PF  2L01-");

        serial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial.setText("-             -            -");

        cantidadrequerida.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida.setText("00001");

        cantidadfinal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal.setText("00000");

        javax.swing.GroupLayout NPSLayout = new javax.swing.GroupLayout(NPS);
        NPS.setLayout(NPSLayout);
        NPSLayout.setHorizontalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addComponent(npecaneado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addComponent(DISP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida)
                                .addGap(28, 28, 28)
                                .addComponent(FQT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal)))
                        .addGap(12, 12, 12)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        NPSLayout.setVerticalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear)
                    .addComponent(QT)
                    .addComponent(FQT)
                    .addComponent(cantidadrequerida)
                    .addComponent(cantidadfinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP)
                    .addComponent(idsp)
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado)
                    .addComponent(serial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque1_1Layout = new javax.swing.GroupLayout(bloque1_1);
        bloque1_1.setLayout(bloque1_1Layout);
        bloque1_1Layout.setHorizontalGroup(
            bloque1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bloque1_1Layout.setVerticalGroup(
            bloque1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque1_1Layout.createSequentialGroup()
                .addComponent(NPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bloque2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS3.setFocusable(false);
        NPS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS3MouseClicked(evt);
            }
        });

        npaescanear3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear3.setText("69Y1649");

        QT3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT3.setText("QT:");

        FQT3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT3.setText("FQT:");

        DISP3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP3.setText("IDSP:");

        idsp3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp3.setText("A");

        descripcion3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion3.setText("LINE CORD XXA / 250V");

        npecaneado3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado3.setText("PF  2L01-");

        serial3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial3.setText("-             -            -");

        cantidadrequerida3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida3.setText("00001");

        cantidadfinal3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal3.setText("00000");

        javax.swing.GroupLayout NPS3Layout = new javax.swing.GroupLayout(NPS3);
        NPS3.setLayout(NPS3Layout);
        NPS3Layout.setHorizontalGroup(
            NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS3Layout.createSequentialGroup()
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(npecaneado3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial3))
                    .addGroup(NPS3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DISP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp3)
                        .addGap(48, 48, 48)
                        .addComponent(descripcion3))
                    .addGroup(NPS3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(npaescanear3)
                        .addGap(31, 31, 31)
                        .addComponent(QT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadrequerida3)
                        .addGap(22, 22, 22)
                        .addComponent(FQT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NPS3Layout.setVerticalGroup(
            NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear3)
                    .addComponent(QT3)
                    .addComponent(FQT3)
                    .addComponent(cantidadrequerida3)
                    .addComponent(cantidadfinal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP3)
                    .addComponent(idsp3)
                    .addComponent(descripcion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado3)
                    .addComponent(serial3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS2.setFocusable(false);
        NPS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS2MouseClicked(evt);
            }
        });

        npaescanear2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear2.setText("69Y1649");

        QT2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT2.setText("QT:");

        FQT2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT2.setText("FQT:");

        DISP2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP2.setText("IDSP:");

        idsp2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp2.setText("A");

        descripcion2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion2.setText("LINE CORD XXA / 250V");

        npecaneado2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado2.setText("PF  2L01-");

        serial2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial2.setText("-             -            -");

        cantidadrequerida2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida2.setText("00001");

        cantidadfinal2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal2.setText("00000");

        javax.swing.GroupLayout NPS2Layout = new javax.swing.GroupLayout(NPS2);
        NPS2.setLayout(NPS2Layout);
        NPS2Layout.setHorizontalGroup(
            NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(npecaneado2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serial2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NPS2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(npaescanear2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadrequerida2)
                .addGap(18, 18, 18)
                .addComponent(FQT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadfinal2)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NPS2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(DISP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idsp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descripcion2)
                .addGap(58, 58, 58))
        );
        NPS2Layout.setVerticalGroup(
            NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear2)
                    .addComponent(QT2)
                    .addComponent(FQT2)
                    .addComponent(cantidadrequerida2)
                    .addComponent(cantidadfinal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP2)
                    .addComponent(idsp2)
                    .addComponent(descripcion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado2)
                    .addComponent(serial2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS1.setFocusable(false);
        NPS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS1MouseClicked(evt);
            }
        });

        npaescanear1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear1.setText("69Y1649");

        QT1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT1.setText("QT:");

        FQT1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT1.setText("FQT:");

        DISP1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP1.setText("IDSP:");

        idsp1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp1.setText("A");

        descripcion1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion1.setText("LINE CORD XXA / 250V");

        npecaneado1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado1.setText("PF  2L01-");

        serial1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial1.setText("-             -            -");

        cantidadrequerida1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida1.setText("00001");

        cantidadfinal1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal1.setText("00000");

        javax.swing.GroupLayout NPS1Layout = new javax.swing.GroupLayout(NPS1);
        NPS1.setLayout(NPS1Layout);
        NPS1Layout.setHorizontalGroup(
            NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS1Layout.createSequentialGroup()
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(DISP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp1)
                        .addGap(53, 53, 53)
                        .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NPS1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(npecaneado1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NPS1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(npaescanear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadrequerida1)
                .addGap(12, 12, 12)
                .addComponent(FQT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadfinal1)
                .addGap(44, 44, 44))
        );
        NPS1Layout.setVerticalGroup(
            NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear1)
                    .addComponent(QT1)
                    .addComponent(FQT1)
                    .addComponent(cantidadrequerida1)
                    .addComponent(cantidadfinal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP1)
                    .addComponent(idsp1)
                    .addComponent(descripcion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado1)
                    .addComponent(serial1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS5.setFocusable(false);
        NPS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS5MouseClicked(evt);
            }
        });

        npaescanear5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear5.setText("69Y1649");

        QT5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT5.setText("QT:");

        FQT5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT5.setText("FQT:");

        DISP5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP5.setText("IDSP:");

        idsp5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp5.setText("A");

        descripcion5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion5.setText("LINE CORD XXA / 250V");

        npecaneado5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado5.setText("PF  2L01-");

        serial5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial5.setText("-             -            -");

        cantidadrequerida5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida5.setText("00001");

        cantidadfinal5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal5.setText("00000");

        javax.swing.GroupLayout NPS5Layout = new javax.swing.GroupLayout(NPS5);
        NPS5.setLayout(NPS5Layout);
        NPS5Layout.setHorizontalGroup(
            NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS5Layout.createSequentialGroup()
                .addGroup(NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPS5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(npaescanear5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QT5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadrequerida5)
                        .addGap(18, 18, 18)
                        .addComponent(FQT5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal5))
                    .addGroup(NPS5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(npecaneado5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addGroup(NPS5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(DISP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idsp5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descripcion5)
                .addGap(53, 53, 53))
        );
        NPS5Layout.setVerticalGroup(
            NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear5)
                    .addComponent(QT5)
                    .addComponent(FQT5)
                    .addComponent(cantidadrequerida5)
                    .addComponent(cantidadfinal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP5)
                    .addComponent(idsp5)
                    .addComponent(descripcion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado5)
                    .addComponent(serial5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque2Layout = new javax.swing.GroupLayout(bloque2);
        bloque2.setLayout(bloque2Layout);
        bloque2Layout.setHorizontalGroup(
            bloque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bloque2Layout.setVerticalGroup(
            bloque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque2Layout.createSequentialGroup()
                .addComponent(NPS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(NPS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        change1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change1.setText("Incompleto");
        change1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(change1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(change1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque1Layout = new javax.swing.GroupLayout(bloque1);
        bloque1.setLayout(bloque1Layout);
        bloque1Layout.setHorizontalGroup(
            bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque1Layout.createSequentialGroup()
                .addGroup(bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bloque2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloque1_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        bloque1Layout.setVerticalGroup(
            bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bloque1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bloque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bloque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1358, Short.MAX_VALUE))
        );

        cuerpo.setViewportView(bloque1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(User500, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(Cntr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(173, 173, 173)
                                                        .addComponent(jLabel6)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(168, 168, 168))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(267, 267, 267)
                                                .addComponent(jLabel8)
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)))))
                                .addComponent(work500, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(146, 146, 146)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel14))
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Cntr)
                                .addComponent(jLabel1))
                            .addComponent(work500, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(User500, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 2010, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 2252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void NPS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS1MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp1.getText().equals("A")){
                all.barcode_1.setVisible(true);
                all.barcode_1.machinefinal.setVisible(false);
                all.barcode_1.machine.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "No se puede volver a escaner...");
            }
        } else {
            pn = this.npaescanear.getText().toUpperCase();
            this.NPS1.setBackground(Color.black);
            this.DISP1.setForeground(Color.white);
            this.FQT1.setForeground(Color.white);
            this.QT1.setForeground(Color.white);
            this.cantidadfinal1.setForeground(Color.white);
            this.cantidadrequerida1.setForeground(Color.white);
            this.descripcion1.setForeground(Color.white);
            this.idsp1.setForeground(Color.white);
            this.npaescanear1.setForeground(Color.white);
            this.npecaneado1.setForeground(Color.white);
            this.serial1.setForeground(Color.white);
        }
    }//GEN-LAST:event_NPS1MouseClicked

    private void NPS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS3MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp3.getText().equals("A")){
                all.barcode_3.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "No se puede volver a escaner...");
            }
        } else {
            this.NPS3.setBackground(Color.black);
            this.DISP3.setForeground(Color.white);
            this.FQT3.setForeground(Color.white);
            this.QT3.setForeground(Color.white);
            this.cantidadfinal3.setForeground(Color.white);
            this.cantidadrequerida3.setForeground(Color.white);
            this.descripcion3.setForeground(Color.white);
            this.idsp3.setForeground(Color.white);
            this.npaescanear3.setForeground(Color.white);
            this.npecaneado3.setForeground(Color.white);
            this.serial3.setForeground(Color.white);
        }
    }//GEN-LAST:event_NPS3MouseClicked

    private void NPS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS2MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp2.getText().equals("A")){
                all.barcode_2.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "No se puede volver a escaner...");
            }
        } else {
            this.NPS2.setBackground(Color.black);
            this.DISP2.setForeground(Color.white);
            this.FQT2.setForeground(Color.white);
            this.QT2.setForeground(Color.white);
            this.cantidadfinal2.setForeground(Color.white);
            this.cantidadrequerida2.setForeground(Color.white);
            this.descripcion2.setForeground(Color.white);
            this.idsp2.setForeground(Color.white);
            this.npaescanear2.setForeground(Color.white);
            this.npecaneado2.setForeground(Color.white);
            this.serial2.setForeground(Color.white);
        }
    }//GEN-LAST:event_NPS2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Map<String, String[]> map = new HashMap <>();
        map.put("01KL468", label3);
        map.put("46C6380", label4);
        map.put("69Y1649", label3);
        System.out.println(Arrays.toString(label3));
        System.out.println("lo que hay aqui en 486:" + Arrays.toString(map.get("01KL468")));
        System.out.println("lo que hay aqui en 380:" + Arrays.toString(map.get("46C6380")));
        nps = map.get(pn);
        System.out.println(pn);
        System.out.println(Arrays.toString(nps));
        if (nps == label1){
            all.barcode.setVisible(true);
        }
        if (nps == label2){
            all.barcode_1.setVisible(true);
        }
        if (nps == label3){
            all.barcode_2.setVisible(true);
        }
        if (nps == label4){
            all.barcode_3.setVisible(true);
        }
        //for (int i = 0; i < nps.length; i++){
          //  if (nps[i].Arraysequals(label1)){
            //}
        //}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x =evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_formMouseDragged

    private void changeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_changeStateChanged
        if (idsp.getText().equals("I")){
            change.setText("Completo");
        }
    }//GEN-LAST:event_changeStateChanged

    private void NPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPSMouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp.getText().equals("A")){
                all.barcode.setVisible(true);
                all.barcode.machinefinal.setVisible(false);
                all.barcode.machine.setVisible(false);
                all.barcode.country.setVisible(false);
                all.barcode.countryfinal.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se puede volver a escaner...");
            }
        } else {
            pn = this.npaescanear.getText().toUpperCase();
            this.NPS.setBackground(Color.black);
            this.DISP.setForeground(Color.white);
            this.FQT.setForeground(Color.white);
            this.QT.setForeground(Color.white);
            this.cantidadfinal.setForeground(Color.white);
            this.cantidadrequerida.setForeground(Color.white);
            this.descripcion.setForeground(Color.white);
            this.idsp.setForeground(Color.white);
            this.npaescanear.setForeground(Color.white);
            this.npecaneado.setForeground(Color.white);
            this.serial.setForeground(Color.white);
        }
    }//GEN-LAST:event_NPSMouseClicked

    private void NPS5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS5MouseClicked

    private void change1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change1StateChanged
        //if (idsp1.getText() && idsp2.getText().equals("I")){
          //  change.setText("Completo");
        //}
    }//GEN-LAST:event_change1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cntr;
    public javax.swing.JLabel DISP;
    public javax.swing.JLabel DISP1;
    public javax.swing.JLabel DISP2;
    public javax.swing.JLabel DISP3;
    public javax.swing.JLabel DISP4;
    public javax.swing.JLabel DISP5;
    public javax.swing.JLabel FQT;
    public javax.swing.JLabel FQT1;
    public javax.swing.JLabel FQT2;
    public javax.swing.JLabel FQT3;
    public javax.swing.JLabel FQT4;
    public javax.swing.JLabel FQT5;
    public javax.swing.JPanel NPS;
    public javax.swing.JPanel NPS1;
    public javax.swing.JPanel NPS2;
    public javax.swing.JPanel NPS3;
    private javax.swing.JPanel NPS4;
    public javax.swing.JPanel NPS5;
    public javax.swing.JLabel QT;
    public javax.swing.JLabel QT1;
    public javax.swing.JLabel QT2;
    public javax.swing.JLabel QT3;
    public javax.swing.JLabel QT4;
    public javax.swing.JLabel QT5;
    public javax.swing.JLabel User500;
    public javax.swing.JPanel bloque1;
    public javax.swing.JPanel bloque1_1;
    private javax.swing.JPanel bloque1_2;
    public javax.swing.JPanel bloque2;
    public javax.swing.JLabel cantidadfinal;
    public javax.swing.JLabel cantidadfinal1;
    public javax.swing.JLabel cantidadfinal2;
    public javax.swing.JLabel cantidadfinal3;
    public javax.swing.JLabel cantidadfinal4;
    public javax.swing.JLabel cantidadfinal5;
    public javax.swing.JLabel cantidadrequerida;
    public javax.swing.JLabel cantidadrequerida1;
    public javax.swing.JLabel cantidadrequerida2;
    public javax.swing.JLabel cantidadrequerida3;
    public javax.swing.JLabel cantidadrequerida4;
    public javax.swing.JLabel cantidadrequerida5;
    public javax.swing.JCheckBox change;
    public javax.swing.JCheckBox change1;
    public javax.swing.JScrollPane cuerpo;
    public javax.swing.JLabel descripcion;
    public javax.swing.JLabel descripcion1;
    public javax.swing.JLabel descripcion2;
    public javax.swing.JLabel descripcion3;
    public javax.swing.JLabel descripcion4;
    public javax.swing.JLabel descripcion5;
    public javax.swing.JLabel idsp;
    public javax.swing.JLabel idsp1;
    public javax.swing.JLabel idsp2;
    public javax.swing.JLabel idsp3;
    public javax.swing.JLabel idsp4;
    public javax.swing.JLabel idsp5;
    public javax.swing.JPanel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel npaescanear;
    public javax.swing.JLabel npaescanear1;
    public javax.swing.JLabel npaescanear2;
    public javax.swing.JLabel npaescanear3;
    public javax.swing.JLabel npaescanear4;
    public javax.swing.JLabel npaescanear5;
    public javax.swing.JLabel npecaneado;
    public javax.swing.JLabel npecaneado1;
    public javax.swing.JLabel npecaneado2;
    public javax.swing.JLabel npecaneado3;
    public javax.swing.JLabel npecaneado4;
    public javax.swing.JLabel npecaneado5;
    public javax.swing.JLabel serial;
    public javax.swing.JLabel serial1;
    public javax.swing.JLabel serial2;
    public javax.swing.JLabel serial3;
    public javax.swing.JLabel serial4;
    public javax.swing.JLabel serial5;
    public javax.swing.JLabel work500;
    // End of variables declaration//GEN-END:variables
}
