/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Imagen_Material_Bisagras_Del_111 extends javax.swing.JPanel {

    /**
     * Creates new form Imagen_Material_Bisagras_Del_111
     */
    public Imagen_Material_Bisagras_Del_111() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen_Material_Bisagra_Del_111 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        change14 = new javax.swing.JCheckBox();

        Imagen_Material_Bisagra_Del_111.setBackground(new java.awt.Color(255, 255, 255));
        Imagen_Material_Bisagra_Del_111.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/BIZAADE.jpg"))); // NOI18N

        change14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change14.setText("Incompleto");
        change14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change14StateChanged(evt);
            }
        });
        change14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Imagen_Material_Bisagra_Del_111Layout = new javax.swing.GroupLayout(Imagen_Material_Bisagra_Del_111);
        Imagen_Material_Bisagra_Del_111.setLayout(Imagen_Material_Bisagra_Del_111Layout);
        Imagen_Material_Bisagra_Del_111Layout.setHorizontalGroup(
            Imagen_Material_Bisagra_Del_111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagen_Material_Bisagra_Del_111Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Imagen_Material_Bisagra_Del_111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(change14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Imagen_Material_Bisagra_Del_111Layout.setVerticalGroup(
            Imagen_Material_Bisagra_Del_111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagen_Material_Bisagra_Del_111Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen_Material_Bisagra_Del_111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen_Material_Bisagra_Del_111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void change14StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change14StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_change14StateChanged

    private void change14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Imagen_Material_Bisagra_Del_111;
    public javax.swing.JCheckBox change14;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
