/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Imagen_Material_Cable_Material extends javax.swing.JPanel {

    /**
     * Creates new form Imagen_Material_Cable_Material
     */
    public Imagen_Material_Cable_Material() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen_cable_monitor = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        change11 = new javax.swing.JCheckBox();

        Imagen_cable_monitor.setBackground(new java.awt.Color(255, 255, 255));
        Imagen_cable_monitor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/POWTF5CA.jpg"))); // NOI18N

        change11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change11.setText("Incompleto");
        change11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change11StateChanged(evt);
            }
        });
        change11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Imagen_cable_monitorLayout = new javax.swing.GroupLayout(Imagen_cable_monitor);
        Imagen_cable_monitor.setLayout(Imagen_cable_monitorLayout);
        Imagen_cable_monitorLayout.setHorizontalGroup(
            Imagen_cable_monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagen_cable_monitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Imagen_cable_monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(change11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Imagen_cable_monitorLayout.setVerticalGroup(
            Imagen_cable_monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Imagen_cable_monitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen_cable_monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen_cable_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void change11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change11StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_change11StateChanged

    private void change11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Imagen_cable_monitor;
    public javax.swing.JCheckBox change11;
    private javax.swing.JLabel jLabel19;
    // End of variables declaration//GEN-END:variables
}
