/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Imagen_pdu_485 extends javax.swing.JPanel {

    /**
     * Creates new form Imagen_pdu_485
     */
    public Imagen_pdu_485() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloqueimagen3 = new javax.swing.JPanel();
        prueba = new javax.swing.JLabel();
        change5 = new javax.swing.JCheckBox();

        bloqueimagen3.setBackground(new java.awt.Color(255, 255, 255));
        bloqueimagen3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        prueba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/PDUVERT.jpg"))); // NOI18N

        change5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change5.setText("Incompleto");
        change5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change5StateChanged(evt);
            }
        });
        change5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bloqueimagen3Layout = new javax.swing.GroupLayout(bloqueimagen3);
        bloqueimagen3.setLayout(bloqueimagen3Layout);
        bloqueimagen3Layout.setHorizontalGroup(
            bloqueimagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloqueimagen3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bloqueimagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prueba)
                    .addComponent(change5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bloqueimagen3Layout.setVerticalGroup(
            bloqueimagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloqueimagen3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prueba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change5)
                .addContainerGap(2796, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloqueimagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloqueimagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void change5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change5StateChanged
        if (all.material_pdu_485.idsp10.getText().equals("I") && all.material_pdu_485.idsp13.getText().equals("I") && all.material_pdu_485.idsp14.getText().equals("I") && all.material_pdu_485.idsp15.getText().equals("I") && all.material_pdu_485.idsp16.getText().equals("I") && all.material_pdu_485.idsp17.getText().equals("I") && all.material_pdu_485.idsp18.getText().equals("I") && all.material_pdu_485.idsp19.getText().equals("I") && all.material_pdu_485.idsp20.getText().equals("I") && all.material_pdu_485.idsp21.getText().equals("I") && all.material_pdu_485.idsp22.getText().equals("I") && all.material_pdu_485.idsp23.getText().equals("I")){
            change5.setSelected(true);
            change5ActionPerformed(null);
        }
    }//GEN-LAST:event_change5StateChanged

    private void change5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change5ActionPerformed
        if (change5.isSelected()){
            change5.setText("Completo");
        } else {
            change5.setText("Incompleto");
        }
    }//GEN-LAST:event_change5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bloqueimagen3;
    public javax.swing.JCheckBox change5;
    public javax.swing.JLabel prueba;
    // End of variables declaration//GEN-END:variables
}
