/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Imagen_material_bisagras_del_421 extends javax.swing.JPanel {

    /**
     * Creates new form Imagen_material_bisagras_del_421
     */
    public Imagen_material_bisagras_del_421() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloquebisagras = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        change7 = new javax.swing.JCheckBox();

        bloquebisagras.setBackground(new java.awt.Color(255, 255, 255));
        bloquebisagras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mfs/Img/BIZAADE2.jpg"))); // NOI18N

        change7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        change7.setText("Incompleto");
        change7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change7StateChanged(evt);
            }
        });
        change7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bloquebisagrasLayout = new javax.swing.GroupLayout(bloquebisagras);
        bloquebisagras.setLayout(bloquebisagrasLayout);
        bloquebisagrasLayout.setHorizontalGroup(
            bloquebisagrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloquebisagrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bloquebisagrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(change7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bloquebisagrasLayout.setVerticalGroup(
            bloquebisagrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloquebisagrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloquebisagras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloquebisagras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void change7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change7StateChanged
        if (all.material_bisagras_del_421.idsp28.getText().equals("I") && all.material_bisagras_del_421.idsp30.getText().equals("I") && all.material_bisagras_del_421.idsp31.getText().equals("I")){
            change7.setSelected(true);
            change7ActionPerformed(null);
        }
    }//GEN-LAST:event_change7StateChanged

    private void change7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change7ActionPerformed
        if (change7.isSelected()){
            change7.setText("Completo");
        } else {
            change7.setText("Incompleto");
        }
    }//GEN-LAST:event_change7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bloquebisagras;
    public javax.swing.JCheckBox change7;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables
}
