/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

import java.awt.Color;
import javax.swing.JOptionPane;
import static mfs.Empty.nm;
import static mfs.Empty.pn;
import static mfs.Empty.pn2;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Material_Rack extends javax.swing.JPanel {

    /**
     * Creates new form Material_Rack
     */
    public Material_Rack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloque1_1 = new javax.swing.JPanel();
        NPS = new javax.swing.JPanel();
        npaescanear = new javax.swing.JLabel();
        QT = new javax.swing.JLabel();
        FQT = new javax.swing.JLabel();
        DISP = new javax.swing.JLabel();
        idsp = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        npecaneado = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        cantidadrequerida = new javax.swing.JLabel();
        cantidadfinal = new javax.swing.JLabel();

        bloque1_1.setBackground(new java.awt.Color(255, 255, 255));
        bloque1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS.setBackground(new java.awt.Color(255, 255, 255));
        NPS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS.setFocusable(false);
        NPS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NPSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NPSFocusLost(evt);
            }
        });
        NPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NPSMousePressed(evt);
            }
        });
        NPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NPSKeyTyped(evt);
            }
        });

        npaescanear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear.setText("01KL468");

        QT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT.setText("QT:");

        FQT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT.setText("FQT:");

        DISP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP.setText("IDSP:");

        idsp.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp.setText("A");

        descripcion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion.setText("MECH        C-rack +pallet");

        npecaneado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado.setText("PF  2L01-");

        serial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial.setText("-             -            -");

        cantidadrequerida.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida.setText("00001");

        cantidadfinal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal.setText("00001");

        javax.swing.GroupLayout NPSLayout = new javax.swing.GroupLayout(NPS);
        NPS.setLayout(NPSLayout);
        NPSLayout.setHorizontalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addComponent(npecaneado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(NPSLayout.createSequentialGroup()
                        .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addComponent(DISP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NPSLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida)
                                .addGap(28, 28, 28)
                                .addComponent(FQT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal)))
                        .addGap(12, 12, 12)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        NPSLayout.setVerticalGroup(
            NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear)
                    .addComponent(QT)
                    .addComponent(FQT)
                    .addComponent(cantidadrequerida)
                    .addComponent(cantidadfinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP)
                    .addComponent(idsp)
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado)
                    .addComponent(serial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque1_1Layout = new javax.swing.GroupLayout(bloque1_1);
        bloque1_1.setLayout(bloque1_1Layout);
        bloque1_1Layout.setHorizontalGroup(
            bloque1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bloque1_1Layout.setVerticalGroup(
            bloque1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque1_1Layout.createSequentialGroup()
                .addComponent(NPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 530, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NPSFocusGained
        this.NPS.setBackground(Color.black);
        this.DISP.setForeground(Color.white);
        this.FQT.setForeground(Color.white);
        this.QT.setForeground(Color.white);
        this.cantidadfinal.setForeground(Color.white);
        this.cantidadrequerida.setForeground(Color.white);
        this.descripcion.setForeground(Color.white);
        this.idsp.setForeground(Color.white);
        this.npaescanear.setForeground(Color.white);
        this.npecaneado.setForeground(Color.white);
        this.serial.setForeground(Color.white);
    }//GEN-LAST:event_NPSFocusGained

    private void NPSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NPSFocusLost
       /* this.NPS.setBackground(Color.WHITE);
        this.DISP.setForeground(Color.BLACK);
        this.FQT.setForeground(Color.BLACK);
        this.QT.setForeground(Color.BLACK);
        this.cantidadfinal.setForeground(Color.BLACK);
        this.cantidadrequerida.setForeground(Color.BLACK);
        this.descripcion.setForeground(Color.BLACK);
        this.idsp.setForeground(Color.BLACK);
        this.npaescanear.setForeground(Color.BLACK);
        this.npecaneado.setForeground(Color.BLACK);
        this.serial.setForeground(Color.BLACK);*/
    }//GEN-LAST:event_NPSFocusLost

    private void NPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPSMouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp.getText().equals("A")){
                pn = this.npaescanear.getText().toUpperCase();
                pn2 = this.npaescanear.getText().substring(3).toUpperCase();
                nm = 0;
                all.f2_funcion.Funcion_F2();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Part to Add");
            }
        }  else if (evt.getClickCount()== 1) {
            NPSFocusGained(null);
            pn = this.npaescanear.getText().toUpperCase();
            pn2 = this.npaescanear.getText().substring(3).toUpperCase();
            nm = 0;
            this.NPS.setBackground(Color.black);
            this.DISP.setForeground(Color.white);
            this.FQT.setForeground(Color.white);
            this.QT.setForeground(Color.white);
            this.cantidadfinal.setForeground(Color.white);
            this.cantidadrequerida.setForeground(Color.white);
            this.descripcion.setForeground(Color.white);
            this.idsp.setForeground(Color.white);
            this.npaescanear.setForeground(Color.white);
            this.npecaneado.setForeground(Color.white);
            this.serial.setForeground(Color.white); 
        }
    }//GEN-LAST:event_NPSMouseClicked

    private void NPSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPSMousePressed

    }//GEN-LAST:event_NPSMousePressed

    private void NPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPSKeyTyped
      /*  char flechas = evt.getKeyChar();
        if (flechas == KeyEvent.VK_DOWN){
            NPSFocusLost (null);
        }*/
    }//GEN-LAST:event_NPSKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DISP;
    public javax.swing.JLabel FQT;
    public javax.swing.JPanel NPS;
    public javax.swing.JLabel QT;
    public javax.swing.JPanel bloque1_1;
    public javax.swing.JLabel cantidadfinal;
    public javax.swing.JLabel cantidadrequerida;
    public javax.swing.JLabel descripcion;
    public javax.swing.JLabel idsp;
    public javax.swing.JLabel npaescanear;
    public javax.swing.JLabel npecaneado;
    public javax.swing.JLabel serial;
    // End of variables declaration//GEN-END:variables
}
