/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Material_Cable_Monitor extends javax.swing.JPanel {

    /**
     * Creates new form Material_Cable_Monitor
     */
    public Material_Cable_Monitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cable_monitor = new javax.swing.JPanel();
        NPS124 = new javax.swing.JPanel();
        npaescanear124 = new javax.swing.JLabel();
        QT124 = new javax.swing.JLabel();
        FQT124 = new javax.swing.JLabel();
        DISP124 = new javax.swing.JLabel();
        idsp124 = new javax.swing.JLabel();
        descripcion124 = new javax.swing.JLabel();
        npecaneado124 = new javax.swing.JLabel();
        serial124 = new javax.swing.JLabel();
        cantidadrequerida124 = new javax.swing.JLabel();
        cantidadfinal124 = new javax.swing.JLabel();

        Cable_monitor.setBackground(new java.awt.Color(255, 255, 255));
        Cable_monitor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS124.setBackground(new java.awt.Color(255, 255, 255));
        NPS124.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS124.setFocusable(false);
        NPS124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS124MouseClicked(evt);
            }
        });

        npaescanear124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear124.setText("00RY699");

        QT124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT124.setText("QT:");

        FQT124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT124.setText("FQT:");

        DISP124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP124.setText("IDSP:");

        idsp124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp124.setText("A");

        descripcion124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion124.setText("LINE CORD C14-C5 AB140");

        npecaneado124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado124.setText("PF  2L01");

        serial124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial124.setText("-             -            -");

        cantidadrequerida124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida124.setText("00001");

        cantidadfinal124.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal124.setText("00000");

        javax.swing.GroupLayout NPS124Layout = new javax.swing.GroupLayout(NPS124);
        NPS124.setLayout(NPS124Layout);
        NPS124Layout.setHorizontalGroup(
            NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS124Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS124Layout.createSequentialGroup()
                        .addComponent(npecaneado124, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial124, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(NPS124Layout.createSequentialGroup()
                        .addGroup(NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS124Layout.createSequentialGroup()
                                .addComponent(DISP124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion124, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NPS124Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida124)
                                .addGap(28, 28, 28)
                                .addComponent(FQT124)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal124)))
                        .addGap(12, 12, 12)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        NPS124Layout.setVerticalGroup(
            NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS124Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear124)
                    .addComponent(QT124)
                    .addComponent(FQT124)
                    .addComponent(cantidadrequerida124)
                    .addComponent(cantidadfinal124))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP124)
                    .addComponent(idsp124)
                    .addComponent(descripcion124))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS124Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado124)
                    .addComponent(serial124))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Cable_monitorLayout = new javax.swing.GroupLayout(Cable_monitor);
        Cable_monitor.setLayout(Cable_monitorLayout);
        Cable_monitorLayout.setHorizontalGroup(
            Cable_monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS124, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Cable_monitorLayout.setVerticalGroup(
            Cable_monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cable_monitorLayout.createSequentialGroup()
                .addComponent(NPS124, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cable_monitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cable_monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPS124MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS124MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS124MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cable_monitor;
    public javax.swing.JLabel DISP124;
    public javax.swing.JLabel FQT124;
    public javax.swing.JPanel NPS124;
    public javax.swing.JLabel QT124;
    public javax.swing.JLabel cantidadfinal124;
    public javax.swing.JLabel cantidadrequerida124;
    public javax.swing.JLabel descripcion124;
    public javax.swing.JLabel idsp124;
    public javax.swing.JLabel npaescanear124;
    public javax.swing.JLabel npecaneado124;
    public javax.swing.JLabel serial124;
    // End of variables declaration//GEN-END:variables
}
