/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Material_Llantas extends javax.swing.JPanel {

    /**
     * Creates new form Material_Llantas
     */
    public Material_Llantas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Material_Llantas = new javax.swing.JPanel();
        NPS129 = new javax.swing.JPanel();
        npaescanear129 = new javax.swing.JLabel();
        QT129 = new javax.swing.JLabel();
        FQT129 = new javax.swing.JLabel();
        DISP129 = new javax.swing.JLabel();
        idsp129 = new javax.swing.JLabel();
        descripcion129 = new javax.swing.JLabel();
        npecaneado129 = new javax.swing.JLabel();
        serial129 = new javax.swing.JLabel();
        cantidadrequerida129 = new javax.swing.JLabel();
        cantidadfinal129 = new javax.swing.JLabel();
        NPS130 = new javax.swing.JPanel();
        npaescanear130 = new javax.swing.JLabel();
        QT130 = new javax.swing.JLabel();
        FQT130 = new javax.swing.JLabel();
        DISP130 = new javax.swing.JLabel();
        idsp130 = new javax.swing.JLabel();
        descripcion130 = new javax.swing.JLabel();
        npecaneado130 = new javax.swing.JLabel();
        serial130 = new javax.swing.JLabel();
        cantidadrequerida130 = new javax.swing.JLabel();
        cantidadfinal130 = new javax.swing.JLabel();
        NPS131 = new javax.swing.JPanel();
        npaescanear131 = new javax.swing.JLabel();
        QT131 = new javax.swing.JLabel();
        FQT131 = new javax.swing.JLabel();
        DISP131 = new javax.swing.JLabel();
        idsp131 = new javax.swing.JLabel();
        descripcion131 = new javax.swing.JLabel();
        npecaneado131 = new javax.swing.JLabel();
        serial131 = new javax.swing.JLabel();
        cantidadrequerida131 = new javax.swing.JLabel();
        cantidadfinal131 = new javax.swing.JLabel();

        Material_Llantas.setBackground(new java.awt.Color(255, 255, 255));
        Material_Llantas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS129.setBackground(new java.awt.Color(255, 255, 255));
        NPS129.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS129.setFocusable(false);
        NPS129.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS129MouseClicked(evt);
            }
        });

        npaescanear129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear129.setText("03FP121");

        QT129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT129.setText("QT:");

        FQT129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT129.setText("FQT:");

        DISP129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP129.setText("IDSP:");

        idsp129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp129.setText("A");

        descripcion129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion129.setText("BRACKET     Outrigger Asm");

        npecaneado129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado129.setText("PF  2L01");

        serial129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial129.setText("-             -            -");

        cantidadrequerida129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida129.setText("00002");

        cantidadfinal129.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal129.setText("00000");

        javax.swing.GroupLayout NPS129Layout = new javax.swing.GroupLayout(NPS129);
        NPS129.setLayout(NPS129Layout);
        NPS129Layout.setHorizontalGroup(
            NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS129Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS129Layout.createSequentialGroup()
                        .addComponent(npecaneado129, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial129, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(NPS129Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(npaescanear129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QT129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadrequerida129)
                        .addGap(28, 28, 28)
                        .addComponent(FQT129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal129)
                        .addGap(12, 12, 12))
                    .addGroup(NPS129Layout.createSequentialGroup()
                        .addComponent(DISP129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion129)
                        .addGap(3, 3, 3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        NPS129Layout.setVerticalGroup(
            NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS129Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear129)
                    .addComponent(QT129)
                    .addComponent(FQT129)
                    .addComponent(cantidadrequerida129)
                    .addComponent(cantidadfinal129))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP129)
                    .addComponent(idsp129)
                    .addComponent(descripcion129))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS129Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado129)
                    .addComponent(serial129))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS130.setBackground(new java.awt.Color(255, 255, 255));
        NPS130.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS130.setFocusable(false);
        NPS130.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS130MouseClicked(evt);
            }
        });

        npaescanear130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear130.setText("03FP123");

        QT130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT130.setText("QT:");

        FQT130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT130.setText("FQT:");

        DISP130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP130.setText("IDSP:");

        idsp130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp130.setText("A");

        descripcion130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion130.setText("BRACKET     Outrig HoldDwn");

        npecaneado130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado130.setText("PF  2L01");

        serial130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial130.setText("-             -            -");

        cantidadrequerida130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida130.setText("00002");

        cantidadfinal130.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal130.setText("00000");

        javax.swing.GroupLayout NPS130Layout = new javax.swing.GroupLayout(NPS130);
        NPS130.setLayout(NPS130Layout);
        NPS130Layout.setHorizontalGroup(
            NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS130Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS130Layout.createSequentialGroup()
                        .addComponent(npecaneado130, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial130, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NPS130Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(npaescanear130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QT130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadrequerida130)
                        .addGap(28, 28, 28)
                        .addComponent(FQT130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal130)
                        .addGap(12, 12, 12))
                    .addGroup(NPS130Layout.createSequentialGroup()
                        .addComponent(DISP130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion130)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NPS130Layout.setVerticalGroup(
            NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS130Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear130)
                    .addComponent(QT130)
                    .addComponent(FQT130)
                    .addComponent(cantidadrequerida130)
                    .addComponent(cantidadfinal130))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP130)
                    .addComponent(idsp130)
                    .addComponent(descripcion130))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS130Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado130)
                    .addComponent(serial130))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS131.setBackground(new java.awt.Color(255, 255, 255));
        NPS131.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS131.setFocusable(false);
        NPS131.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS131MouseClicked(evt);
            }
        });

        npaescanear131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear131.setText("46K4308");

        QT131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT131.setText("QT:");

        FQT131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT131.setText("FQT:");

        DISP131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP131.setText("IDSP:");

        idsp131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp131.setText("A");

        descripcion131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion131.setText("SCREW M6x13HexFlange");

        npecaneado131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado131.setText("PF  2L01");

        serial131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial131.setText("-             -            -");

        cantidadrequerida131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida131.setText("00004");

        cantidadfinal131.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal131.setText("00000");

        javax.swing.GroupLayout NPS131Layout = new javax.swing.GroupLayout(NPS131);
        NPS131.setLayout(NPS131Layout);
        NPS131Layout.setHorizontalGroup(
            NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS131Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS131Layout.createSequentialGroup()
                        .addGroup(NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS131Layout.createSequentialGroup()
                                .addComponent(npecaneado131, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serial131, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(NPS131Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear131)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT131)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida131)
                                .addGap(28, 28, 28)
                                .addComponent(FQT131)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal131)
                                .addGap(12, 12, 12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NPS131Layout.createSequentialGroup()
                        .addComponent(DISP131)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp131)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion131)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        NPS131Layout.setVerticalGroup(
            NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS131Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear131)
                    .addComponent(QT131)
                    .addComponent(FQT131)
                    .addComponent(cantidadrequerida131)
                    .addComponent(cantidadfinal131))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP131)
                    .addComponent(idsp131)
                    .addComponent(descripcion131))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS131Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado131)
                    .addComponent(serial131))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Material_LlantasLayout = new javax.swing.GroupLayout(Material_Llantas);
        Material_Llantas.setLayout(Material_LlantasLayout);
        Material_LlantasLayout.setHorizontalGroup(
            Material_LlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS129, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS130, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS131, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Material_LlantasLayout.setVerticalGroup(
            Material_LlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Material_LlantasLayout.createSequentialGroup()
                .addComponent(NPS129, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS131, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2076, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Material_Llantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Material_Llantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPS129MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS129MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS129MouseClicked

    private void NPS130MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS130MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS130MouseClicked

    private void NPS131MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS131MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS131MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DISP129;
    public javax.swing.JLabel DISP130;
    public javax.swing.JLabel DISP131;
    public javax.swing.JLabel FQT129;
    public javax.swing.JLabel FQT130;
    public javax.swing.JLabel FQT131;
    private javax.swing.JPanel Imagen_Material_Ext_Denali;
    private javax.swing.JPanel Material_Llantas;
    public javax.swing.JPanel NPS129;
    public javax.swing.JPanel NPS130;
    public javax.swing.JPanel NPS131;
    public javax.swing.JLabel QT129;
    public javax.swing.JLabel QT130;
    public javax.swing.JLabel QT131;
    public javax.swing.JLabel cantidadfinal129;
    public javax.swing.JLabel cantidadfinal130;
    public javax.swing.JLabel cantidadfinal131;
    public javax.swing.JLabel cantidadrequerida129;
    public javax.swing.JLabel cantidadrequerida130;
    public javax.swing.JLabel cantidadrequerida131;
    public javax.swing.JCheckBox change14;
    public javax.swing.JLabel descripcion129;
    public javax.swing.JLabel descripcion130;
    public javax.swing.JLabel descripcion131;
    public javax.swing.JLabel idsp129;
    public javax.swing.JLabel idsp130;
    public javax.swing.JLabel idsp131;
    private javax.swing.JLabel jLabel25;
    public javax.swing.JLabel npaescanear129;
    public javax.swing.JLabel npaescanear130;
    public javax.swing.JLabel npaescanear131;
    public javax.swing.JLabel npecaneado129;
    public javax.swing.JLabel npecaneado130;
    public javax.swing.JLabel npecaneado131;
    public javax.swing.JLabel serial129;
    public javax.swing.JLabel serial130;
    public javax.swing.JLabel serial131;
    // End of variables declaration//GEN-END:variables
}
