/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

import java.awt.Color;
import javax.swing.JOptionPane;
import static mfs.Empty.nm;
import static mfs.Empty.pn;
import static mfs.Empty.pn2;

public class Material_etiqueta_534 extends javax.swing.JPanel {

    /**
     * Creates new form Material_etiqueta_534
     */
    public Material_etiqueta_534() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloque3 = new javax.swing.JPanel();
        NPS4 = new javax.swing.JPanel();
        npaescanear4 = new javax.swing.JLabel();
        QT4 = new javax.swing.JLabel();
        FQT4 = new javax.swing.JLabel();
        DISP4 = new javax.swing.JLabel();
        idsp4 = new javax.swing.JLabel();
        descripcion4 = new javax.swing.JLabel();
        npecaneado4 = new javax.swing.JLabel();
        serial4 = new javax.swing.JLabel();
        cantidadrequerida4 = new javax.swing.JLabel();
        cantidadfinal4 = new javax.swing.JLabel();
        NPS6 = new javax.swing.JPanel();
        npaescanear6 = new javax.swing.JLabel();
        QT6 = new javax.swing.JLabel();
        FQT6 = new javax.swing.JLabel();
        DISP6 = new javax.swing.JLabel();
        idsp6 = new javax.swing.JLabel();
        descripcion6 = new javax.swing.JLabel();
        npecaneado6 = new javax.swing.JLabel();
        serial6 = new javax.swing.JLabel();
        cantidadrequerida6 = new javax.swing.JLabel();
        cantidadfinal6 = new javax.swing.JLabel();

        bloque3.setBackground(new java.awt.Color(255, 255, 255));
        bloque3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS4.setBackground(new java.awt.Color(255, 255, 255));
        NPS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS4.setFocusable(false);
        NPS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS4MouseClicked(evt);
            }
        });

        npaescanear4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear4.setText("03FP534");

        QT4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT4.setText("QT:");

        FQT4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT4.setText("FQT:");

        DISP4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP4.setText("IDSP:");

        idsp4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp4.setText("A");

        descripcion4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion4.setText("ARTWORK  S42AGENCY LABEL");

        npecaneado4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado4.setText("PF  2L01-");

        serial4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial4.setText("-             -            -");

        cantidadrequerida4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida4.setText("00001");

        cantidadfinal4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal4.setText("00000");

        javax.swing.GroupLayout NPS4Layout = new javax.swing.GroupLayout(NPS4);
        NPS4.setLayout(NPS4Layout);
        NPS4Layout.setHorizontalGroup(
            NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS4Layout.createSequentialGroup()
                        .addComponent(npecaneado4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NPS4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(npaescanear4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(QT4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadrequerida4)
                        .addGap(28, 28, 28)
                        .addComponent(FQT4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadfinal4)
                        .addGap(21, 21, 21))
                    .addGroup(NPS4Layout.createSequentialGroup()
                        .addComponent(DISP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion4)))
                .addGap(21, 21, 21))
        );
        NPS4Layout.setVerticalGroup(
            NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear4)
                    .addComponent(QT4)
                    .addComponent(FQT4)
                    .addComponent(cantidadrequerida4)
                    .addComponent(cantidadfinal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP4)
                    .addComponent(idsp4)
                    .addComponent(descripcion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado4)
                    .addComponent(serial4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS6.setBackground(new java.awt.Color(255, 255, 255));
        NPS6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS6.setFocusable(false);
        NPS6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS6MouseClicked(evt);
            }
        });

        npaescanear6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear6.setText("44V4664");

        QT6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT6.setText("QT:");

        FQT6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT6.setText("FQT:");

        DISP6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP6.setText("IDSP:");

        idsp6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp6.setText("A");

        descripcion6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion6.setText("LABEL SYS LBL - RIBBON");

        npecaneado6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado6.setText("PF  2L01-");

        serial6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial6.setText("-             -            -");

        cantidadrequerida6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida6.setText("00001");

        cantidadfinal6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal6.setText("00000");

        javax.swing.GroupLayout NPS6Layout = new javax.swing.GroupLayout(NPS6);
        NPS6.setLayout(NPS6Layout);
        NPS6Layout.setHorizontalGroup(
            NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS6Layout.createSequentialGroup()
                        .addComponent(npecaneado6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(NPS6Layout.createSequentialGroup()
                        .addGroup(NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS6Layout.createSequentialGroup()
                                .addComponent(DISP6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NPS6Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida6)
                                .addGap(28, 28, 28)
                                .addComponent(FQT6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal6)))
                        .addGap(12, 12, 12)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        NPS6Layout.setVerticalGroup(
            NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear6)
                    .addComponent(QT6)
                    .addComponent(FQT6)
                    .addComponent(cantidadrequerida6)
                    .addComponent(cantidadfinal6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP6)
                    .addComponent(idsp6)
                    .addComponent(descripcion6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado6)
                    .addComponent(serial6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque3Layout = new javax.swing.GroupLayout(bloque3);
        bloque3.setLayout(bloque3Layout);
        bloque3Layout.setHorizontalGroup(
            bloque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bloque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NPS4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NPS6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        bloque3Layout.setVerticalGroup(
            bloque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque3Layout.createSequentialGroup()
                .addComponent(NPS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS4MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp4.getText().equals("A")){
                pn = this.npaescanear4.getText().toUpperCase();
                pn2 = this.npaescanear4.getText().substring(3).toUpperCase();
                nm = 4;
                all.f2_funcion.Funcion_F2();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Part to Add");
            }
        } /*else {
            pn = this.npaescanear4.getText().toUpperCase();
            pn2 = this.npaescanear4.getText().substring(3).toUpperCase();
            nm = 4;
            this.NPS4.setBackground(Color.black);
            this.DISP4.setForeground(Color.white);
            this.FQT4.setForeground(Color.white);
            this.QT4.setForeground(Color.white);
            this.cantidadfinal4.setForeground(Color.white);
            this.cantidadrequerida4.setForeground(Color.white);
            this.descripcion4.setForeground(Color.white);
            this.idsp4.setForeground(Color.white);
            this.npaescanear4.setForeground(Color.white);
            this.npecaneado4.setForeground(Color.white);
            this.serial4.setForeground(Color.white);
        }*/
    }//GEN-LAST:event_NPS4MouseClicked

    private void NPS6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS6MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp6.getText().equals("A")){
                pn = this.npaescanear6.getText().toUpperCase();
                pn2 = this.npaescanear6.getText().substring(3).toUpperCase();
                nm = 6;
                all.f2_funcion.Funcion_F2();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Part to Add");
            }
        } /*else {
            pn = this.npaescanear6.getText().toUpperCase();
            pn2 = this.npaescanear6.getText().substring(3).toUpperCase();
            nm = 6;
            this.NPS6.setBackground(Color.black);
            this.DISP6.setForeground(Color.white);
            this.FQT6.setForeground(Color.white);
            this.QT6.setForeground(Color.white);
            this.cantidadfinal6.setForeground(Color.white);
            this.cantidadrequerida6.setForeground(Color.white);
            this.descripcion6.setForeground(Color.white);
            this.idsp6.setForeground(Color.white);
            this.npaescanear6.setForeground(Color.white);
            this.npecaneado6.setForeground(Color.white);
            this.serial6.setForeground(Color.white);
        }*/
    }//GEN-LAST:event_NPS6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DISP4;
    public javax.swing.JLabel DISP6;
    public javax.swing.JLabel FQT4;
    public javax.swing.JLabel FQT6;
    public javax.swing.JPanel NPS4;
    public javax.swing.JPanel NPS6;
    public javax.swing.JLabel QT4;
    public javax.swing.JLabel QT6;
    public javax.swing.JPanel bloque3;
    public javax.swing.JLabel cantidadfinal4;
    public javax.swing.JLabel cantidadfinal6;
    public javax.swing.JLabel cantidadrequerida4;
    public javax.swing.JLabel cantidadrequerida6;
    public javax.swing.JLabel descripcion4;
    public javax.swing.JLabel descripcion6;
    public javax.swing.JLabel idsp4;
    public javax.swing.JLabel idsp6;
    public javax.swing.JLabel npaescanear4;
    public javax.swing.JLabel npaescanear6;
    public javax.swing.JLabel npecaneado4;
    public javax.swing.JLabel npecaneado6;
    public javax.swing.JLabel serial4;
    public javax.swing.JLabel serial6;
    // End of variables declaration//GEN-END:variables
}
