package mfs;

import java.awt.Color;
import javax.swing.JOptionPane;
import static mfs.Empty.nm;
import static mfs.Empty.pn;
import static mfs.Empty.pn2;

public class Material_etiqueta_1952 extends javax.swing.JPanel {

    /**
     * Creates new form Material_etiqueta_1952
     */
    public Material_etiqueta_1952() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloque5 = new javax.swing.JPanel();
        NPS9 = new javax.swing.JPanel();
        npaescanear9 = new javax.swing.JLabel();
        QT9 = new javax.swing.JLabel();
        FQT9 = new javax.swing.JLabel();
        DISP9 = new javax.swing.JLabel();
        idsp9 = new javax.swing.JLabel();
        descripcion9 = new javax.swing.JLabel();
        npecaneado9 = new javax.swing.JLabel();
        serial9 = new javax.swing.JLabel();
        cantidadrequerida9 = new javax.swing.JLabel();
        cantidadfinal9 = new javax.swing.JLabel();

        bloque5.setBackground(new java.awt.Color(255, 255, 255));
        bloque5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS9.setBackground(new java.awt.Color(255, 255, 255));
        NPS9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS9.setFocusable(false);
        NPS9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS9MouseClicked(evt);
            }
        });

        npaescanear9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear9.setText("39J1952");

        QT9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT9.setText("QT:");

        FQT9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT9.setText("FQT:");

        DISP9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP9.setText("IDSP:");

        idsp9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp9.setText("A");

        descripcion9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion9.setText("LABEL, WEEE");

        npecaneado9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado9.setText("PF  2L01-");

        serial9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial9.setText("-             -            -");

        cantidadrequerida9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida9.setText("00001");

        cantidadfinal9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal9.setText("00000");

        javax.swing.GroupLayout NPS9Layout = new javax.swing.GroupLayout(NPS9);
        NPS9.setLayout(NPS9Layout);
        NPS9Layout.setHorizontalGroup(
            NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS9Layout.createSequentialGroup()
                        .addComponent(npecaneado9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(NPS9Layout.createSequentialGroup()
                        .addGroup(NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS9Layout.createSequentialGroup()
                                .addComponent(DISP9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NPS9Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida9)
                                .addGap(28, 28, 28)
                                .addComponent(FQT9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal9)))
                        .addGap(12, 12, 12)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        NPS9Layout.setVerticalGroup(
            NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear9)
                    .addComponent(QT9)
                    .addComponent(FQT9)
                    .addComponent(cantidadrequerida9)
                    .addComponent(cantidadfinal9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP9)
                    .addComponent(idsp9)
                    .addComponent(descripcion9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado9)
                    .addComponent(serial9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bloque5Layout = new javax.swing.GroupLayout(bloque5);
        bloque5.setLayout(bloque5Layout);
        bloque5Layout.setHorizontalGroup(
            bloque5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bloque5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NPS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bloque5Layout.setVerticalGroup(
            bloque5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloque5Layout.createSequentialGroup()
                .addComponent(NPS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bloque5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPS9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS9MouseClicked
        if (evt.getClickCount()>1){
            if (this.idsp9.getText().equals("A")){
                pn = this.npaescanear9.getText().toUpperCase();
                pn2 = this.npaescanear9.getText().substring(3).toUpperCase();
                nm = 9;
                all.f2_funcion.Funcion_F2();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Part to Add");
            }
        } /*else {
            pn = this.npaescanear9.getText().toUpperCase();
            pn2 = this.npaescanear9.getText().substring(3).toUpperCase();
            nm = 9;
            this.NPS9.setBackground(Color.black);
            this.DISP9.setForeground(Color.white);
            this.FQT9.setForeground(Color.white);
            this.QT9.setForeground(Color.white);
            this.cantidadfinal9.setForeground(Color.white);
            this.cantidadrequerida9.setForeground(Color.white);
            this.descripcion9.setForeground(Color.white);
            this.idsp9.setForeground(Color.white);
            this.npaescanear9.setForeground(Color.white);
            this.npecaneado9.setForeground(Color.white);
            this.serial9.setForeground(Color.white);
        }*/
    }//GEN-LAST:event_NPS9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DISP9;
    public javax.swing.JLabel FQT9;
    public javax.swing.JPanel NPS9;
    public javax.swing.JLabel QT9;
    public javax.swing.JPanel bloque5;
    public javax.swing.JLabel cantidadfinal9;
    public javax.swing.JLabel cantidadrequerida9;
    public javax.swing.JLabel descripcion9;
    public javax.swing.JLabel idsp9;
    public javax.swing.JLabel npaescanear9;
    public javax.swing.JLabel npecaneado9;
    public javax.swing.JLabel serial9;
    // End of variables declaration//GEN-END:variables
}
