/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mfs;

/**
 *
 * @author MelquiAzarelRamirezR
 */
public class Material_Bisagras_Del_111 extends javax.swing.JPanel {

    /**
     * Creates new form Material_Bisagras_Del_111
     */
    public Material_Bisagras_Del_111() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        NPS136 = new javax.swing.JPanel();
        npaescanear136 = new javax.swing.JLabel();
        QT136 = new javax.swing.JLabel();
        FQT136 = new javax.swing.JLabel();
        DISP136 = new javax.swing.JLabel();
        idsp136 = new javax.swing.JLabel();
        descripcion136 = new javax.swing.JLabel();
        npecaneado136 = new javax.swing.JLabel();
        serial136 = new javax.swing.JLabel();
        cantidadrequerida136 = new javax.swing.JLabel();
        cantidadfinal136 = new javax.swing.JLabel();
        NPS137 = new javax.swing.JPanel();
        npaescanear137 = new javax.swing.JLabel();
        QT137 = new javax.swing.JLabel();
        FQT137 = new javax.swing.JLabel();
        DISP137 = new javax.swing.JLabel();
        idsp137 = new javax.swing.JLabel();
        descripcion137 = new javax.swing.JLabel();
        npecaneado137 = new javax.swing.JLabel();
        serial137 = new javax.swing.JLabel();
        cantidadrequerida137 = new javax.swing.JLabel();
        cantidadfinal137 = new javax.swing.JLabel();
        NPS138 = new javax.swing.JPanel();
        npaescanear138 = new javax.swing.JLabel();
        QT138 = new javax.swing.JLabel();
        FQT138 = new javax.swing.JLabel();
        DISP138 = new javax.swing.JLabel();
        idsp138 = new javax.swing.JLabel();
        descripcion138 = new javax.swing.JLabel();
        npecaneado138 = new javax.swing.JLabel();
        serial138 = new javax.swing.JLabel();
        cantidadrequerida138 = new javax.swing.JLabel();
        cantidadfinal138 = new javax.swing.JLabel();
        NPS139 = new javax.swing.JPanel();
        npaescanear139 = new javax.swing.JLabel();
        QT139 = new javax.swing.JLabel();
        FQT139 = new javax.swing.JLabel();
        DISP139 = new javax.swing.JLabel();
        idsp139 = new javax.swing.JLabel();
        descripcion139 = new javax.swing.JLabel();
        npecaneado139 = new javax.swing.JLabel();
        serial139 = new javax.swing.JLabel();
        cantidadrequerida139 = new javax.swing.JLabel();
        cantidadfinal139 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NPS136.setBackground(new java.awt.Color(255, 255, 255));
        NPS136.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS136.setFocusable(false);
        NPS136.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS136MouseClicked(evt);
            }
        });

        npaescanear136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear136.setText("01KU111");

        QT136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT136.setText("QT:");

        FQT136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT136.setText("FQT:");

        DISP136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP136.setText("IDSP:");

        idsp136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp136.setText("A");

        descripcion136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion136.setText("HINGE hinge tall pn");

        npecaneado136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado136.setText("PF  2L01");

        serial136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial136.setText("-             -            -");

        cantidadrequerida136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida136.setText("00001");

        cantidadfinal136.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal136.setText("00000");

        javax.swing.GroupLayout NPS136Layout = new javax.swing.GroupLayout(NPS136);
        NPS136.setLayout(NPS136Layout);
        NPS136Layout.setHorizontalGroup(
            NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS136Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS136Layout.createSequentialGroup()
                        .addComponent(npecaneado136, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serial136, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NPS136Layout.createSequentialGroup()
                        .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NPS136Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear136))
                            .addGroup(NPS136Layout.createSequentialGroup()
                                .addComponent(DISP136)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idsp136)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion136, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(NPS136Layout.createSequentialGroup()
                                .addComponent(QT136)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida136)
                                .addGap(28, 28, 28)
                                .addComponent(FQT136)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal136)))
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NPS136Layout.setVerticalGroup(
            NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS136Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear136)
                    .addComponent(QT136)
                    .addComponent(FQT136)
                    .addComponent(cantidadrequerida136)
                    .addComponent(cantidadfinal136))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP136)
                    .addComponent(idsp136)
                    .addComponent(descripcion136))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS136Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado136)
                    .addComponent(serial136))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS137.setBackground(new java.awt.Color(255, 255, 255));
        NPS137.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS137.setFocusable(false);
        NPS137.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS137MouseClicked(evt);
            }
        });

        npaescanear137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear137.setText("01KU112");

        QT137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT137.setText("QT:");

        FQT137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT137.setText("FQT:");

        DISP137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP137.setText("IDSP:");

        idsp137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp137.setText("A");

        descripcion137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion137.setText("HINGE Hinge short pn     ");

        npecaneado137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado137.setText("PF  2L01");

        serial137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial137.setText("-             -            -");

        cantidadrequerida137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida137.setText("00001");

        cantidadfinal137.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal137.setText("00000");

        javax.swing.GroupLayout NPS137Layout = new javax.swing.GroupLayout(NPS137);
        NPS137.setLayout(NPS137Layout);
        NPS137Layout.setHorizontalGroup(
            NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS137Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS137Layout.createSequentialGroup()
                        .addGroup(NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS137Layout.createSequentialGroup()
                                .addComponent(npecaneado137, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serial137, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(NPS137Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear137)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT137)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida137)
                                .addGap(28, 28, 28)
                                .addComponent(FQT137)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal137)
                                .addGap(12, 12, 12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NPS137Layout.createSequentialGroup()
                        .addComponent(DISP137)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp137)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion137)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        NPS137Layout.setVerticalGroup(
            NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS137Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear137)
                    .addComponent(QT137)
                    .addComponent(FQT137)
                    .addComponent(cantidadrequerida137)
                    .addComponent(cantidadfinal137))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP137)
                    .addComponent(idsp137)
                    .addComponent(descripcion137))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS137Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado137)
                    .addComponent(serial137))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS138.setBackground(new java.awt.Color(255, 255, 255));
        NPS138.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS138.setFocusable(false);
        NPS138.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS138MouseClicked(evt);
            }
        });

        npaescanear138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear138.setText("01KU137");

        QT138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT138.setText("QT:");

        FQT138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT138.setText("FQT:");

        DISP138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP138.setText("IDSP:");

        idsp138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp138.setText("A");

        descripcion138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion138.setText("BRACKET Latch Bracket    ");

        npecaneado138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado138.setText("PF  2L01");

        serial138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial138.setText("-             -            -");

        cantidadrequerida138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida138.setText("00001");

        cantidadfinal138.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal138.setText("00000");

        javax.swing.GroupLayout NPS138Layout = new javax.swing.GroupLayout(NPS138);
        NPS138.setLayout(NPS138Layout);
        NPS138Layout.setHorizontalGroup(
            NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS138Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS138Layout.createSequentialGroup()
                        .addGroup(NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS138Layout.createSequentialGroup()
                                .addComponent(npecaneado138, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serial138, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(NPS138Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear138)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QT138)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida138)
                                .addGap(28, 28, 28)
                                .addComponent(FQT138)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal138)
                                .addGap(12, 12, 12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NPS138Layout.createSequentialGroup()
                        .addComponent(DISP138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion138)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        NPS138Layout.setVerticalGroup(
            NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS138Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear138)
                    .addComponent(QT138)
                    .addComponent(FQT138)
                    .addComponent(cantidadrequerida138)
                    .addComponent(cantidadfinal138))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP138)
                    .addComponent(idsp138)
                    .addComponent(descripcion138))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS138Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado138)
                    .addComponent(serial138))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NPS139.setBackground(new java.awt.Color(255, 255, 255));
        NPS139.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NPS139.setFocusable(false);
        NPS139.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NPS139MouseClicked(evt);
            }
        });

        npaescanear139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npaescanear139.setText("46C6380");

        QT139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        QT139.setText("QT:");

        FQT139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FQT139.setText("FQT:");

        DISP139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DISP139.setText("IDSP:");

        idsp139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idsp139.setText("A");

        descripcion139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        descripcion139.setText("SCREW M5x16 BLACK");

        npecaneado139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        npecaneado139.setText("PF  2L01");

        serial139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        serial139.setText("-             -            -");

        cantidadrequerida139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadrequerida139.setText("00006");

        cantidadfinal139.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cantidadfinal139.setText("00000");

        javax.swing.GroupLayout NPS139Layout = new javax.swing.GroupLayout(NPS139);
        NPS139.setLayout(NPS139Layout);
        NPS139Layout.setHorizontalGroup(
            NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS139Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NPS139Layout.createSequentialGroup()
                        .addGroup(NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NPS139Layout.createSequentialGroup()
                                .addComponent(npecaneado139, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serial139, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(NPS139Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(npaescanear139)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(QT139)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadrequerida139)
                                .addGap(28, 28, 28)
                                .addComponent(FQT139)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadfinal139)
                                .addGap(12, 12, 12)))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(NPS139Layout.createSequentialGroup()
                        .addComponent(DISP139)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idsp139)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descripcion139)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        NPS139Layout.setVerticalGroup(
            NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPS139Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaescanear139)
                    .addComponent(QT139)
                    .addComponent(FQT139)
                    .addComponent(cantidadrequerida139)
                    .addComponent(cantidadfinal139))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISP139)
                    .addComponent(idsp139)
                    .addComponent(descripcion139))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPS139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npecaneado139)
                    .addComponent(serial139))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NPS136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS138, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NPS139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(NPS136, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS137, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS138, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPS139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NPS136MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS136MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS136MouseClicked

    private void NPS137MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS137MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS137MouseClicked

    private void NPS138MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS138MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS138MouseClicked

    private void NPS139MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NPS139MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NPS139MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DISP136;
    public javax.swing.JLabel DISP137;
    public javax.swing.JLabel DISP138;
    public javax.swing.JLabel DISP139;
    public javax.swing.JLabel FQT136;
    public javax.swing.JLabel FQT137;
    public javax.swing.JLabel FQT138;
    public javax.swing.JLabel FQT139;
    public javax.swing.JPanel NPS136;
    public javax.swing.JPanel NPS137;
    public javax.swing.JPanel NPS138;
    public javax.swing.JPanel NPS139;
    public javax.swing.JLabel QT136;
    public javax.swing.JLabel QT137;
    public javax.swing.JLabel QT138;
    public javax.swing.JLabel QT139;
    public javax.swing.JLabel cantidadfinal136;
    public javax.swing.JLabel cantidadfinal137;
    public javax.swing.JLabel cantidadfinal138;
    public javax.swing.JLabel cantidadfinal139;
    public javax.swing.JLabel cantidadrequerida136;
    public javax.swing.JLabel cantidadrequerida137;
    public javax.swing.JLabel cantidadrequerida138;
    public javax.swing.JLabel cantidadrequerida139;
    public javax.swing.JLabel descripcion136;
    public javax.swing.JLabel descripcion137;
    public javax.swing.JLabel descripcion138;
    public javax.swing.JLabel descripcion139;
    public javax.swing.JLabel idsp136;
    public javax.swing.JLabel idsp137;
    public javax.swing.JLabel idsp138;
    public javax.swing.JLabel idsp139;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel npaescanear136;
    public javax.swing.JLabel npaescanear137;
    public javax.swing.JLabel npaescanear138;
    public javax.swing.JLabel npaescanear139;
    public javax.swing.JLabel npecaneado136;
    public javax.swing.JLabel npecaneado137;
    public javax.swing.JLabel npecaneado138;
    public javax.swing.JLabel npecaneado139;
    public javax.swing.JLabel serial136;
    public javax.swing.JLabel serial137;
    public javax.swing.JLabel serial138;
    public javax.swing.JLabel serial139;
    // End of variables declaration//GEN-END:variables
}
